### ISSUE TITLE
choose color palette

### ISSUE THREAD

**Issue by tlcoles** [tlcoles/BudgetOnTheGo#6]

**Comment by tlcoles** [comment]
@HenniePenny - you might want to look into the default theme that Chakra offers. Perhaps it's a fine alternative to creating a unique palette https://chakra-ui.com/docs/styled-system/theme

**Comment by HenniePenny** [comment]
I have seen that, too, but I had already created some palettes with coolors.com, so I'd be happy to show you those first.

**Comment by tlcoles** [comment]
No need. I am wholly fine with whatever color scheme is selected, default or custom!

**Comment by HenniePenny** [comment]
![Image](https://user-images.githubusercontent.com/105878812/200943521-ac8708d2-d406-4f15-9b86-af0d6fccda8f.JPG)
